# Generated by Django 4.2.16 on 2024-10-10 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=256)),
                ('age', models.IntegerField(null=True)),
                ('firstname', models.TextField(max_length=128)),
                ('lastname', models.TextField(max_length=128)),
            ],
        ),
    ]
